### PR TITLE
Revert "[bigtable] Bump client version to 0.9.6.2"

### PR DESCRIPTION
**Pull request by gabrielgerhardsson**
Reverts spotify/heroic#281.

### CODE REVIEW

**Comment by udoprog** [comment]
@gabrielgerhardsson what's going on?

**Comment by gabrielgerhardsson** [comment]
@udoprog The previous PR was premature, it turns out. I missed changing in a couple of other places, and when I do now it's not immediately solved. 

I could also just finish the work and merge as another fixup-PR. However, reverting and merging when it's really done seems better. 
What do you think @udoprog?

**Comment by udoprog** [comment]
@gabrielgerhardsson What are the effects? But in general: fix it if quick, otherwise revert :).

**Comment by gabrielgerhardsson** [comment]
@udoprog Building on my machine works fine, but automated build breaks. I'm still investigating. This is why I didn't catch it with a simple reinstall-repackaged && rebuild on my machine.

**Comment by gabrielgerhardsson** [comment]
@udoprog Alright, I'll keep on looking at this and we'll see :)

**Comment by gabrielgerhardsson** [comment]
@udoprog I believe this will require an upgrade of grpc, and a code change due to API change in the bigtable client. So I believe reverting and putting the change out there as a proper PR would be best.

**Pull request merged**
