### PR TITLE
Update dependencies to support Java 9+.

### LINKED ISSUE #442: Update to Java 11
One of the blockers for Java > 8 is lombok which has numerous compatibility issues. Some work has already been done to replace lombok with straight java or kotlin (kotlin preferred for class generation). Fully replacing lombok should be considered a prereq for updating.

### PR DESCRIPTION
**Pull request by hexedpackets**
Resolves #442

### CODE REVIEW

**Comment by lmuhlha** [comment]
I think travis needs an update as well: https://github.com/spotify/heroic/blob/master/.travis.yml#L3

**Comment by lmuhlha** [comment]
and the docs while we're here https://github.com/spotify/heroic/blob/f022d6f7e8eee66e5b2c23d0a0cd078cc5998664/docs/content/_docs/getting_started/compile.html#L17

**Comment by lmuhlha** [comment]
possibly these two as well?
https://github.com/spotify/heroic/blob/master/build.gradle#L228
https://github.com/spotify/heroic/blob/master/build.gradle#L247

**Comment by hexedpackets** [comment]
Good catches (can't respond inline since they weren't code comments). I updated travis and the docs.

jackson-datatype-jdk8 adds datatypes that didn't exist before Java 8, its needed for serializing/deserializing things like Optionals irregardless of using Java 11.

kotlin-stdlib-jdk8 is the same, but for interoperability between Java and Kotlin. Also works and is needed for Java 11.

**Pull request merged**
