### PR TITLE
Trim white space around shell input

### PR DESCRIPTION
**Pull request by PseudoSky**
These have leading spaces
screen shot 2016-01-11 at 12 04 17 pm

I was going to add a test case, but I wasn't positive on how the syntax of QuoteParserTest works.

Would this work?

```
test(Case.of("  trimming_spaces  ", "trimming_spaces"));
```

### CODE REVIEW

**Comment by udoprog** [comment]
@PseudoSky check the test case, you have one failure (leading whitespace after the trim).

**Comment by PseudoSky** [comment]
From what I can tell it looks like the error is 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.13:check (validate) on project heroic-shell: Failed during checkstyle execution: There are 1 checkstyle errors. -> [Help 1]
```

@udoprog does that look right? I don't have too much experience with the testing framework or the style guidelines, do you know where I would look to find out how to fix it?

**Comment by udoprog** [comment]
The line you want to look at is this:

```
[INFO] --- maven-checkstyle-plugin:2.13:check (validate) @ heroic-shell ---
[INFO] Starting audit...
/home/travis/build/spotify/heroic/heroic-shell/src/main/java/com/spotify/heroic/shell/QuoteParser.java:63: error: Line has trailing spaces.
Audit done.
```

It indicates that your line has trailing spaces.

**Comment by PseudoSky** [comment]
Ha sorry the error was too meta for me to see - Trailing spaces within a trailing spaces fix.
I think I fixed it.

**Pull request merged**
