### PR TITLE
Remove static import statement that keep failing sporadically

### PR DESCRIPTION
**Pull request by ao2017**

### CODE REVIEW

**Comment by sming** [comment]
@ao2017 do we have any idea why this is failing in this manner? A SO post or something?

**Comment by ao2017** [comment]
> @ao2017 do we have any idea why this is failing in this manner? A SO post or something?

SO post ???  I am not sure, this PR simply removes the static import statement

**Comment by adsail** [comment]
Which failure in particular is this intending to resolve?

**Comment by ao2017** [comment]
> Which failure in particular is this intending to resolve?

 Failing to find distributions(), its occurs sporadically during compilation.

**Comment by adsail** [comment]
> > Which failure in particular is this intending to resolve?
> 
> Failing to find distributions(), its occurs sporadically during compilation.

I'm still getting the error on my local against this branch.

**Review by adsail — APPROVED** [review]

**Pull request merged**
