### PR TITLE
[datastax] Upgrade & repackage Datastax driver

### PR DESCRIPTION
**Pull request by gabrielgerhardsson**
NOTE: You need to re-run ./tools/install-repackaged after this commit.

* Upgrades Datastax driver to 3.2.0
* Isolates the Datastax driver so that its dependencies doesn't clash
with other Heroic dependencies.

### CODE REVIEW

**Comment by gabrielgerhardsson** [comment]
Integration tests pass, with Cassandra 3.5.

**Comment by udoprog** [comment]
@gabrielgerhardsson cool!

But we need to test it with 2.1.x as well since it's listed in the readme.

**Comment by gabrielgerhardsson** [comment]
@udoprog Ah right, I'm on it.

**Comment by gabrielgerhardsson** [comment]
Now confirmed with Cassandra 2.1 also :)
Merging.

**Pull request merged**
