### PR TITLE
Calculate delta per second

### PR DESCRIPTION
**Pull request by nabam**
This should make delta values independent from resolution

### CODE REVIEW

**Comment by nezdolik** [comment]
Change needs to be backwards compatible, not to impact existing users.

**Comment by dmichel1** [comment]
@nezdolik can we get this merged since the feature has already been released internally?

**Comment by dmichel1** [comment]
@nabam @nezdolik  was the `NotNegative` aggregation added to get around the issue that `Delta` and `DeltaPerSecond` can produce negative values?

I'm looking at adding two more aggregations that are similar to prometheus, `rate()` and `irate()` that work with counters and can handle them being reset without producing negative values.

https://github.com/prometheus/prometheus/blob/2bd510a63e48ac6bf4971d62199bdb1045c93f1a/docs/querying/functions.md#rate

https://github.com/prometheus/prometheus/blob/c6399296dcc059bbc496f40e31aa2c7b7a341951/promql/functions.go#L178

**Comment by nabam** [comment]
@dmichel1 `Average(NotNegative(DeltaPerSecond()))` is essentially a prometheus `rate`. NotNegative is used to drop data points when overflow or restart happens. Without NotNegative it can be used on gauges to get derivatives.

**Comment by dmichel1** [comment]
as discussed - using `NotNegative` will result in a loss of precision when the counter resets. Seems like creating rate/irate is the way forward.

**Pull request merged**
