### PR TITLE
Upgrade and add support for bigtable client 0.9.2

### PR DESCRIPTION
**Pull request by juruen**

### CODE REVIEW

**Comment by udoprog** [comment]
Looks like there are a few new dependencies that could be relocated/ignored:
https://travis-ci.org/spotify/heroic/builds/158793448#L2420
https://travis-ci.org/spotify/heroic/builds/158793448#L2459
https://travis-ci.org/spotify/heroic/builds/158793448#L2471

**Comment by udoprog** [comment]
All in all the patch looks really good.

Renaming `inclusive/exclusive -> open/closed` is a nice touch of the v2 protocol. Just as a comment it is a bit ironic that they have to use the words that they swapped out to describe what it now does :):
https://github.com/googleapis/googleapis/blob/master/google/bigtable/v2/data.proto#L128

 Solving the repackaging conflicts can be done later as long as there are no current fatal classpath issues (just please open an issue about it).

Really nice job, :+1:

**Comment by juruen** [comment]
@udoprog just repackaged those three dependencies.

**Comment by udoprog** [comment]
@juruen LGTM

**Comment by juruen** [comment]
@udoprog thank you :)

**Pull request merged**
